### ISSUE TITLE
Broken blocks and dropped items disappear

### ISSUE THREAD

**Issue by SnazzAzzy** [EnigmaticaModpacks/Enigmatica6#4868]
### Modpack Version

Enigmatica 6 1.2.1

### Describe your issue.

Whenever i break a block or drop an item it disappears. Discovered this because im on a server with friends and one of them got a boomerang that disappeared when he dropped it for me. To be sure, he dropped a few items and i broke a few blocks but they all disappeared. First time encountering this so it might be a new bug but idk. Please help

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
there was an issue with enigmatic graves + the keepinventory gamerule, but that shouldn't appear anymore in the version you claim you play on 🤔

**Comment by Darkere** [comment]
keepinventory was fixed, not sure if the conflict with the heart trinket was fixed though

**Comment by NielsPilgaard** [comment]
Both of those issues were fixed.

Has anyone on the server been using modded shears lately? :P

**Comment by SnazzAzzy** [comment]
its still happening with certain blocks for me idk what it is

**Comment by SnazzAzzy** [comment]
ok seriously getting pissed cuz it seems to be random, cant mine the damn blocks i need and now im never gonna know when its gonna happen someone PLEASE FUCKING HELP

**Comment by NielsPilgaard** [comment]
Calm down and answer my question so I can help you.

**Comment by TechGeekMonster** [comment]
It's could be intense server lag. This sort of problem comes up a lot when my server starts lagging

**Comment by SnazzAzzy** [comment]
> Calm down and answer my question so I can help you.

idk i dont keep up with what the others use

**Comment by SnazzAzzy** [comment]
> It's could be intense server lag. This sort of problem comes up a lot when my server starts lagging

i would believe that, but it happens when theres no one else online and its random as to what blocks actually disappear. there'll be no lag and one time it'll be regular stone that disappears, and another in the same session, i will be able to collect what i wasnt able to before, except now there'll be something else i wont be able to pick up

**Comment by TemperedFool** [comment]
> idk i dont keep up with what the others use
> 
> 

Please find out. Niller isn't asking randomly.

**Comment by NielsPilgaard** [comment]
> > It's could be intense server lag. This sort of problem comes up a lot when my server starts lagging
> 
> i would believe that, but it happens when theres no one else online and its random as to what blocks actually disappear. there'll be no lag and one time it'll be regular stone that disappears, and another in the same session, i will be able to collect what i wasnt able to before, except now there'll be something else i wont be able to pick up

Please supply the server's latest.log and debug.log if possible :)

**Comment by SnazzAzzy** [comment]
> > > It's could be intense server lag. This sort of problem comes up a lot when my server starts lagging
> > 
> > 
> > i would believe that, but it happens when theres no one else online and its random as to what blocks actually disappear. there'll be no lag and one time it'll be regular stone that disappears, and another in the same session, i will be able to collect what i wasnt able to before, except now there'll be something else i wont be able to pick up
> 
> Please supply the server's latest.log and debug.log if possible :)
how do i do that? and they said they havent been using modded shears

**Comment by NielsPilgaard** [comment]
The server's logs folder holds those logs. I'm gonna redirect you to discord now, as I don't think there's a bug here. We'll reopen if we find an issue we can work with.

**Comment by SnazzAzzy** [comment]
> The server's logs folder holds those logs. I'm gonna redirect you to discord now, as I don't think there's a bug here. We'll reopen if we find an issue we can work with.

the mod discord or pvt?
